<?php
// $Id$

/**
 * @file
 * The RealName module allows the admin to choose fields from the user profile
 * that will be used to add a "realname" element (method) to a user object.
 * Hook_user is used to automatically add this to any user object that is loaded.
 *
 * @copyright Copyright (c) 2007-2008 Nancy Wichmann.  All rights reserved.
 */
  define('MODULE_VERSION', '$Id$');

  if (module_exists('token')) {
    include_once(drupal_get_path('module', 'realname') .'/token_realname.inc');
  }

//********************************************************************
//* Drupal Hooks
//********************************************************************/

/**
 * Implementation of hook_help().
 */
function realname_help($path, $args = NULL) {
  switch ($path) {
    case 'admin/user/realname':
      $output = t('This page displays the status of and settings for the RealName module.');
      $output .= '<p>Version: '. MODULE_VERSION .'</p>';
      return $output;

    case 'admin/help#realname':
      return t('This simple module adds a "realname" element (method) to a user object when that object is loaded.');
  }
}

/**
 * Implementation of hook_theme().
 */
function realname_theme() {
  return array(
    'realname_admin_levels' => array(
      'arguments' => array('form' => NULL),
      'file' => 'realname.admin.inc',
      ),
    'realname_new_role' => array(
      'arguments' => array('form' => NULL),
      'file' => 'realname_theme.inc',
      ),
    );
}

/**
 * Implementation of hook_perm().
 */
function realname_perm() {
  return array('use realname');
}

/**
 * Implementation of hook_menu().
 */
function realname_menu() {
  global $user;
  $items = array();

  $items['admin/user/realname'] = array(
    'title' => 'RealName',
    'description' => "Configure which fields are used to create a user's RealName.",
    'access arguments' => array('administer users'),
    'page callback' => 'realname_admin_settings',
    'type' => MENU_NORMAL_ITEM,
    'file' => 'realname.admin.inc',
    );

  $items['admin/user/realname/fields'] = array(
    'title' => 'Fields',
    'access arguments' => array('administer users'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('realname_admin_fields'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'realname.admin.inc',
    'weight' => 0,
    );

  $items['admin/user/realname/general'] = array(
    'title' => 'General',
    'access arguments' => array('administer users'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('realname_admin_general'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'realname.admin.inc',
    'weight' => 2,
    );

  $items['admin/user/realname/module'] = array(
    'title' => 'Module',
    'access arguments' => array('administer users'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('realname_admin_module'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'realname.admin.inc',
    'weight' => 4,
    );

  $items['admin/user/realname/bypass'] = array(
    'title' => 'Bypass Forms',
    'access arguments' => array('administer users'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('realname_admin_bypass'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'realname.admin.inc',
    'weight' => 6,
    );

  return $items;
}

/**
 * Implementation of hook_search().
 */
function realname_search($op = 'search', $keys = null, $skip_access_check = FALSE) {
  switch ($op) {
    case 'name':
      if ($skip_access_check || user_access('access user profiles')) {      
        return t('User name');
      }

    case 'reset':
      variable_set('realname_last_index', -1);
      return;

    case 'status':
      $start = variable_get('realname_last_index', -1) + 1;
      $total = db_result(db_query('SELECT COUNT(*) FROM {users} WHERE status=1'));
      $remaining = db_result(db_query("SELECT COUNT(*) FROM {users} WHERE status=1 AND uid>=%d", $start));
      return array('remaining' => $remaining, 'total' => $total);

    case 'search':
      if ($skip_access_check || user_access('access user profiles')) {      
        $results = array();
        $find = do_search($keys, 'realname');
        foreach ($find as $item) {
          if ($item->type != 'realname') {
            continue;
          }
          $account = db_fetch_object(db_query("SELECT u.uid, u.name, u.picture FROM {users} u WHERE u.uid=%d", $item->sid));
          $realname = realname_make_name($account);
          $results[] = array(
            'link' => url('user/'. $item->sid, array('absolute' => TRUE)),
            'type' => t('User'),
            'title' => $realname,
            'user' => theme('username', $account) . '<div class="clear-block"></div>',
            'score' => $item->score,
            'snippet' => theme('user_picture', $account) . t('Login name: !name', array('!name' => $account->name)),
            );
          }
        return $results;
      }
      else {
       drupal_set_message("you don't have access for RealName.");
      }
  }
}

/**
 * Implementation of hook_update_index().
 */
function realname_update_index() {
  $start = variable_get('realname_last_index', -1) + 1;
 $start = 0;
  $limit = (int)variable_get('search_cron_limit', 100);
  watchdog('RealName',
    'Indexing up to !limit users, starting at !start',
    array('!start' => $start, '!limit' => $limit),
    WATCHDOG_NOTICE);
  $result = db_query_range("SELECT uid, name FROM {users} WHERE status=1 AND uid>=%d", $start, 0, $limit);
  while ($account = db_fetch_object($result)) {
    $realname = realname_make_name($account);
    search_index($account->uid, 'realname', $realname .' '. $account->name);
    variable_set('realname_last_index', $account->uid);
  }
}

/**
 * Implementation of hook_menu_alter().
 */
function realname_menu_alter(&$callbacks) {
  $callbacks['user/%user_uid_optional']['title callback'] = 'realname_user_page_title';
  $callbacks['user/%user_uid_optional']['page callback'] = 'realname_user_view';
  $callbacks['user/%user_category/edit']['page callback'] = 'realname_user_edit';
  if (isset($callbacks['user/%user/track'])) {
    $callbacks['user/%user/track']['page callback'] = 'realname_tracker_page';
  }
  if (isset($callbacks['user/%user/contact'])) {
    $callbacks['user/%user/contact']['page callback'] = 'realname_contact_user';
  }
  if (isset($callbacks['blog/%user_uid_optional'])) {
    $callbacks['blog/%user_uid_optional']['page callback'] = 'realname_blog_page';
  }
}

/**
 * Correct user page breadcrumbs.
 */
function realname_check_breadcrumbs($account) {
  $trail = array(l(t('Home'), ''));
  // If we are looking at someone other than the current user, fix the breadcrumb.
  if ($account->uid != $GLOBALS['user']->uid) {
    $trail[] = decode_entities(l($account->realname, '/user/'. $account->uid));
  }
  $trail = drupal_set_breadcrumb($trail);
}

/**
 * Intercept the user page view. Modified from user.module.
 * Fix some core bugs.
 */
function realname_user_view($account) {
  realname_check_breadcrumbs($account);
  // Retrieve all profile fields and attach to $account->content.
  user_build_content($account);

  // To theme user profiles, copy modules/user/user_profile.tpl.php
  // to your theme directory, and edit it as instructed in that file's comments.
  return theme('user_profile', $account);
}

/**
 * Intercept the user edit page. Modified from user.module.
 * Fix some core bugs.
 */
function realname_user_edit($account, $category = 'account') {
  realname_check_breadcrumbs($account);
  return drupal_get_form('user_profile_form', $account, $category);
}

/**
 * Intercept the user blog page.
 */
function realname_blog_page($account) {
  $output = blog_page_user($account);
  drupal_set_title($title = t("@name's blog", array('@name' => $account->realname)));
  return $output;
}

/**
 * Intercept the tracker page.
 */
function realname_tracker_page($account = NULL, $set_title = FALSE) {
  $output = tracker_page($account, $set_title);
  if ($account) {
    realname_check_breadcrumbs($account);    
    drupal_set_title(realname_user_page_title($account));
  }
  return $output;
}

/**
 * Intercept the Personal contact page.
 */
function realname_contact_user($account) {
  global $user;

  if (!valid_email_address($user->mail)) {
    $output = t('You need to provide a valid e-mail address to contact other users. Please update your <a href="@url">user information</a> and try again.', array('@url' => url("user/$user->uid/edit")));
  }
  else if (!flood_is_allowed('contact', variable_get('contact_hourly_threshold', 3))) {
    $output = t('You cannot contact more than %number users per hour. Please try again later.', array('%number' => variable_get('contact_hourly_threshold', 3)));
  }
  else {
    realname_check_breadcrumbs($account);    
    $output = drupal_get_form('contact_mail_user', $account);
  }

  return $output;
}

/**
 * Intercept the user page title to use the user's name.
 */
function realname_user_page_title($account) {
  $name = (isset($account->realname) ? $account->realname : realname_make_name($account));
  return $name;
}

/**
 * An implementation of hook_theme_registry_alter()
 *
 * Swap in our own replacement for theme_username(), allowing the
 * site admin to configure the string on a per-nodetype basis.
 **/
function realname_theme_registry_alter(&$theme_registry) {
  if (!empty($theme_registry['form_element'])) {
    $path = drupal_get_path('module', 'realname');
    if (variable_get('realname_theme', TRUE)) {
      $theme_registry['username']['function'] = 'realname_username';
      $theme_registry['username']['file'] = $path .'/realname_theme.inc';
      $theme_registry['username']['theme path'] = $path;
      $theme_registry['username']['theme paths'][0] = $path;
    }
    $theme_registry['user_admin_new_role']['function'] = 'theme_realname_new_role';
    $theme_registry['user_admin_new_role']['file'] = $path .'/realname_theme.inc';
    $theme_registry['user_admin_new_role']['theme path'] = $path;
    $theme_registry['user_admin_new_role']['theme paths'][0] = $path;

    $theme_registry['user_picture']['theme path'] = $path;
    $theme_registry['user_picture']['theme paths'][0] = $path;
    foreach ($theme_registry['user_picture']['preprocess functions'] as $key => $value) {
      if ($value == 'template_preprocess_user_picture') {
        $theme_registry['user_picture']['preprocess functions'][$key] = 'template_preprocess_user_picture_realname';
      }
    }    
  }
}

/**
 * Process variables for user-picture.tpl.php (copied from user.module).
 */
function template_preprocess_user_picture_realname(&$variables) {
  $variables['picture'] = '';
  if (variable_get('user_pictures', 0)) {
    $account = $variables['account'];
    if (!empty($account->picture) && file_exists($account->picture)) {
      $picture = file_create_url($account->picture);
    }
    elseif (variable_get('user_picture_default', '')) {
      $picture = variable_get('user_picture_default', '');
    }

    if (isset($picture)) {
      $account->name = isset($account->realname) ? $account->realname : realname_make_name($account);
      $name = $account->name ? $account->name : variable_get('anonymous', t('Anonymous'));
      $alt = t("@user's picture", array('@user' => $name));
      $variables['picture'] = theme('image', $picture, $alt, $alt, '', FALSE);
      if (!empty($account->uid) && user_access('access user profiles')) {
        $attributes = array('attributes' => array('title' => t('View user profile.')), 'html' => TRUE);
        $variables['picture'] = l($variables['picture'], "user/$account->uid", $attributes);
      }
    }
  }
}

/**
 * Implementation of hook_user().
 */
function realname_user($op, &$edit, &$account, $category = NULL) {
  if ($op == 'load') {
    $account->realname = realname_make_name($account);

    // If theme then replace name with realname.
    if (variable_get('realname_theme', TRUE) && $account->realname) {
      //Store it for places where it needed
      if (!isset($account->realname_save) && is_object($account)) {
        $account->realname_save = $account->name;
      }
    }
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function realname_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  static $type;
  static $accounts = array();
  if (!user_access('use realname')) {
    return;
  }

  if (!variable_get('realname_nodeapi', FALSE)) {
    return;
  }
  switch ($op) {
    case 'view':
      // Don't operate on the node type that we are using.
      if (!isset($type)) {
        $type = variable_get('realname_profile_type', NULL);
      }
      if ($node->type == $type) {
        break;
      }
      // Node is being loaded.
      // Save the username that is already there.
      $node->realname_save = $node->name;
      if (!isset($accounts[$node->uid])) {
        $accounts[$node->uid] = realname_get_user($node->uid);
      }
      $account = $accounts[$node->uid];
      $node->realname = $node->name = $account->name;
      $node->homepage = isset($account->homepage) ? $account->homepage : NULL;
      break;

    case 'prepare':
      // Node is about to be edited.
      // Reset the username or save will fail.
      if (isset($node->realname_save)) {
        $node->name = $node->realname_save;
      }
      break;
  }
}

/**
 * Helper to replace user_load() and be much faster.
 */
function realname_get_user($uid) {
  $result = db_query("SELECT uid, name, mail FROM {users} WHERE uid=%d", $uid);
  $account = db_fetch_object($result);
  $account->name = realname_make_name($account);
  return $account;
}

/**
 * Implementation of hook_comment().
 */
function realname_comment(&$comment, $op) {
  static $users = array();
  switch ($op) {
    case 'view':
      if (!$comment->homepage) {
        if (isset($users[$comment->uid])) {
          $account = $users[$comment->uid];
        }
        else {
          $users[$comment->uid] = $account = realname_get_user($comment->uid);
        }
        
        $comment->homepage = isset($account->homepage) ? $account->homepage : NULL;
      }
      break;
  }
  return;
}

/**
 * Implementation of hook_mail_alter().
 * Intercepts the user activation form to show the username.
 */
function realname_mail_alter(&$message) {
  switch ($message['id']) {
    case 'user_status_activated':
      // Look for the "username: " string which precedes the username.
      if (isset($message['params']['account']->realname_save)) {
        $message['body'][0] = str_replace(t('username: ') . $message['params']['account']->name, t('username: ') . $message['params']['account']->realname_save, $message['body'][0]);
      }
  }
}

/**
 * Implementation of hook_form_alter().
 * Intercepts the contact forms to show the realname.
 */
function realname_form_alter(&$form, $form_state, $form_id) {
  global $user;
  if (!user_access('use realname')) {
    return;
  }
//  drupal_set_message($form_id);

  $bypass_forms = variable_get('realname_bypass_forms', array(array('name' => 'comment_form', 'fields' => array('name'))));
  foreach ($bypass_forms as $bypass) {
    // Is it a form the admin wants bypassed?
    if ($form_id == $bypass['name']) {
      $field_name = '$form[\''. implode("']['", $bypass['fields']) ."']['#default_value']";
      if (!isset($user->realname)) {
        $user->realname = realname_make_name($user);
      }
      $value = $user->uid ? $user->realname_save : variable_get('anonymous', 'Anonymous');
      eval($field_name .' = $value;');      
    }
  }

  switch ($form_id) {
    case 'user_profile_form':
      if (variable_get('realname_theme', TRUE)) {
        $form['account']['name']['#default_value'] = $form['_account']['#value']->realname_save;
      }
      break;

    case 'contact_mail_user':
      if (!isset($user->realname)) {
        $user->realname = realname_make_name($user);
      }
      $form['from']['#value'] = check_plain($user->realname) .' &lt;'. check_plain($user->mail) .'&gt;';
      if (!isset($form['recipient']['#value']->realname)) {
        $form['recipient']['#value']->realname = realname_make_name($form['recipient']['#value']);
      }
      $form['to']['#value'] = check_plain($form['recipient']['#value']->realname);
      break;

    case 'contact_mail_page':
      if (!isset($user->realname)) {
        $user->realname = realname_make_name($user);
      }
      $form['name']['#default_value'] = $user->uid ? $user->realname : '';
      break;

    case 'user_admin_role':
      $rid = $form['rid']['#value'];
      $pic = variable_get('realname_user_level_'. $rid, NULL);
      $form['level'] = array(
        '#type' => 'textfield',
        '#default_value' => $pic,
        '#title' => t('User level image'),
        '#description' => t('This image will be shown when the user name is themed.
          It can be used to show special attributes or user participation level.
          The path is relative to the files directory "%files".', array('%files' => file_directory_path())),
        '#field_suffix' => empty($pic) ? '' : '&nbsp;&nbsp;<img src="'. file_create_url($pic) .'" />',
        );

      $form['submit']['#weight'] = 98;
      $form['delete']['#weight'] = 99;
      $form['#submit'][] = '_realname_role_submit';
      break;

//    case 'user_admin_new_role':  // See http://drupal.org/node/392156
//      drupal_set_message(show_array($form));
  }
}

/**
 * Get picture entered on role form.
 */
function _realname_role_submit($form, &$form_state) {
  $rid = $form_state['values']['rid'];
  $pic = $form_state['values']['level'];
  variable_set('realname_user_level_'. $rid, $pic);  
//  drupal_set_message("realname_user_level_$rid => '$pic'");  
}

//********************************************************************
//* Module Functions
//********************************************************************

/**
 * Using selected fields, build the "real name" field in the object.
 *
 * @param
 *   $account - the user object to update.
 *
 * @return
 *   The constructed "real name" string.
 */
function realname_make_name(&$account) {
  static $fields, $pattern_saved, $homepage, $use_theme, $type, $module, $profile_privacy;
  static $users = array();
  static $links = array();
  static $edit = array();

  // Return anonymous user right away.
  if ($account->uid == 0) {
    return $account->name;
  }

  if (isset($users[$account->uid])) {
    $account->homepage = isset($links[$account->uid]) ? $links[$account->uid] : NULL;
    return $users[$account->uid];
  }

  // Get our controlling variables (static makes it once per page load).
  if (!isset($fields)) {
    $fields = variable_get('realname_fields', array());
    // Are there any fields assigned yet?
    if (!$fields) {
      // No, so just return the name.
      return $account->name;
    }
    $pattern_saved = variable_get('realname_pattern', ' ');
    $homepage = variable_get('realname_homepage', NULL);
    $use_theme = variable_get('realname_theme', TRUE);
    $module = variable_get('realname_profile_module', NULL);
    $type = variable_get('realname_profile_type', NULL);
    $profile_privacy = module_exists('profile_privacy');
    if ($module && module_exists($module)) {
      include_once(drupal_get_path('module', 'realname') .'/realname_'. $module .'.inc');
    }
    else {
      drupal_set_message(t('No module is available for RealName.'), 'error');
      return $account->name;
    }
  }
  $pattern = $pattern_saved;

  // Has the module been set up yet?
  if ($fields) {
    // Has the profile been loaded?
    if (!isset($account->{key($fields)})) {
      $load_func = $module .'_load_profile';
      if (!function_exists($load_func)) {
        drupal_set_message(t('The profile load function (!module) was not found.', array('!module' => $load_func)), 'error');
        return $account->name;
      }
      module_invoke($module, 'load_profile', $account, $type);
      if ($profile_privacy) {
        profile_privacy_user('load', $edit, $account);
      }
    }

    $stuff = array();
    $i = 0;
    foreach ($fields as $name => $weight) {
      ++$i;
      $private = 'private_'. $name;
      // This will let you see that a user is using Profile Privacy.
//      if (isset($account->{$private})) {
//        drupal_set_message("$account->name ($account->uid) has marked the $name field as private.");
//      }
      $private_field = isset($account->{$private}) ? $account->{$private} : FALSE;
      if (isset($account->$name) && !empty($account->$name) && !$private_field) {
        if (is_array($account->$name)) {
          $stuff['%'. $i] = $account->{$name}[0]['view'];
        }
        else {
          $stuff['%'. $i] = $account->$name;
        }
      }
      else {
        // If there is no value, remove the pattern piece, except the first.
        $pattern = str_replace('%'. $i, NULL, $pattern);
      }
    }

    // If no fields set, use username.
    if (count($stuff) == 0) {
      $stuff['%1'] = $account->name;
      $pattern = '%1';
    }

    if ($homepage && $account->$homepage) {
      $links[$account->uid] = $account->$homepage;
    }

    $string = trim(strtr($pattern, $stuff));
    $users[$account->uid] = $string;
  }
  else {
    $string = $account->name;
  }
  return $string;
}

/**
 * Provides array sorting function for uasort.
 *  @link http://us2.php.net/manual/en/function.uasort.php PHP Manual @end-link
 *
 * @param
 *   $a - the first array to be compared.
 *
 * @param
 *   $b - the second array to be compared.
 *
 * @return
 *   integer indicating ordering.
 */
function _realname_sort($a, $b) {
  // Sort first by weight.
  $ret = $a['weight'] - $b['weight'];
  if ($ret == 0) {
    // The two are equal, so use the title.
    $ret = strcmp($a['title'], $b['title']);
  }

  return $ret;
}
